# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build

on:
  push:
    branches: ["main", "staging"]
  pull_request:
    branches: ["main", "staging"]

env:
  # This is local hardhat account #7 key.
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  API_PRIVATE_KEY: "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d"
  PROVIDER_URL: ${{ vars.PROVIDER_URL }}
  CHAIN_ID: ${{ vars.CHAIN_ID }}
  SESSION_COOKIE_NAME: ${{ vars.SESSION_COOKIE_NAME }}
  SESSION_COOKIE_PASS: ${{ secrets.SESSION_COOKIE_PASS }}
  DATA_SEAL_PASS: ${{ secrets.DATA_SEAL_PASS }}
  POSTMARK_API_KEY: ${{ secrets.POSTMARK_API_KEY }}
  KV_REST_API_URL: ${{ vars.KV_REST_API_URL }}
  KV_REST_API_TOKEN: ${{ secrets.KV_REST_API_TOKEN }}

jobs:
  build:
    environment: staging
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install
      - run: npx lerna run build
