# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test

on:
  push:
    branches: ["main", "staging"]
  pull_request:
    branches: ["main", "staging"]

env:
  # This is local hardhat account #7 key.
  STORE_PRIVATE_KEY: "0x4bbbf85ce3377467afe5d46f804f221813b2bb87f24d81f60f1fcdbf7cbf4356"
  PROVIDER_URL: "http://127.0.0.1:8546"
  CHAIN: "local-tableland"
  CHAIN_ID: 31337
  SESSION_COOKIE_NAME: "STUDIO_SESSION"
  SESSION_COOKIE_PASS: "ci test session pass ci test session pass ci test session pass"
  DATA_SEAL_PASS: "ci test data seal pass ci test data seal pass ci test data seal pass"
  POSTMARK_API_KEY: ${{ secrets.POSTMARK_API_KEY }}
  KV_REST_API_URL: ${{ vars.KV_REST_API_URL }}
  KV_REST_API_TOKEN: ${{ secrets.KV_REST_API_TOKEN }}

jobs:
  review:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install
      - run: npm run test
